### ISSUE TITLE
hslua-aeson 1.0.2 fails to build with hslua 1.1.1 (despite the package bounds in the .cabal file stating it will)

### ISSUE THREAD

**Issue by phlummox** [tarleb/hslua-aeson#2]
The bounds for compatible versions of hslua are [stated as being](https://github.com/hslua/hslua-aeson/blob/8b986850d3a6bf015038716080519d138a2f88ac/hslua-aeson.cabal#L35)

```
hslua                >= 1.0     && < 1.2
```

but this is not correct - in fact, hslua-aeson 1.0.2 fails to build with hslua 1.1.1.

### Reproducing

* Unpack hslua-aeson 1.0.2 from hackage, `cd` in
* `$ cabal v2-configure --constraint 'hslua ==1.1.1'`
* `$ cabal v2-build`

### Expected result

The package should build without error.

### Actual result

The build fails with the following error:

```
[1 of 1] Compiling Foreign.Lua.Aeson ( src/Foreign/Lua/Aeson.hs, /mnt/data/dev/uwa-marking-scripts/hs-marker-database-hint/XXX/hslua-aeson-1.0.2/dist-newstyle/build/x86_64-linux/ghc-8.6.5/hslua-aeson-1.0.2/build/Foreign/Lua/Aeson.o )

src/Foreign/Lua/Aeson.hs:131:3: error:
    • Couldn't match expected type ‘Lua a1’
                  with actual type ‘[a0] -> Lua ()’
    • In a stmt of a 'do' block: pushList . toList $ v
      In the expression:
        do pushList . toList $ v
           push (fromIntegral (Vector.length v) :: Lua.Integer)
           rawseti (- 2) 0
      In an equation for ‘pushvector’:
          pushvector v
            = do pushList . toList $ v
                 push (fromIntegral (Vector.length v) :: Lua.Integer)
                 rawseti (- 2) 0
    |
131 |   pushList . toList $ v
    |   ^^^^^^^^^^^^^^^^^^^^^

src/Foreign/Lua/Aeson.hs:131:14: error:
    • Couldn't match type ‘[a]’ with ‘a0 -> Lua ()’
      Expected type: Vector a -> Foreign.Lua.Push.Pusher a0
        Actual type: Vector a -> [a]
    • In the second argument of ‘(.)’, namely ‘toList’
      In the expression: pushList . toList
      In a stmt of a 'do' block: pushList . toList $ v
    • Relevant bindings include
        v :: Vector a (bound at src/Foreign/Lua/Aeson.hs:130:12)
        pushvector :: Vector a -> Lua ()
          (bound at src/Foreign/Lua/Aeson.hs:130:1)
    |
131 |   pushList . toList $ v
    |              ^^^^^^

```

Gist of the failing build is [here](https://gist.github.com/phlummox/8f1638f2e9b06089b8426e2fa91e1b32#file-error-txt).

### Cause

This is because hslua 1.1.1 introduces breaking changes - the signature of `Foreign.Lua.pushList` has changed (see https://github.com/hslua/hslua/issues/83).

A fix is to apply the following patch:

```patch
diff a/src/Foreign/Lua/Aeson.hs b/src/Foreign/Lua/Aeson.hs
--- a/src/Foreign/Lua/Aeson.hs
+++ b/src/Foreign/Lua/Aeson.hs
@@ -1,5 +1,7 @@
 {-# OPTIONS_GHC -fno-warn-orphans #-}
 {-# LANGUAGE LambdaCase #-}
+{-# LANGUAGE CPP #-}
+
 {-|
 Module      :  Foreign.Lua.Aeson
 Copyright   :  © 2017–2020 Albert Krewinkel
@@ -128,7 +130,11 @@ isNull idx = do
 -- | Push a vector unto the stack.
 pushvector :: Pushable a => Vector a -> Lua ()
 pushvector v = do
+#if MIN_VERSION_hslua(1,1,1)
+  pushList push $ toList v
+#else
   pushList . toList $ v
+#endif
   push (fromIntegral (Vector.length v) :: Lua.Integer)
   rawseti (-2) 0
```
If you like, I can submit a pull request of the change from [here](https://github.com/phlummox/hslua-aeson/commit/f93d8c748451d97a97c7d4b566f0af715c0f0cf0).

**Comment by tarleb** [comment]
Thanks, embarrassing mistake. This is fixed by doing a hackage revision, excluding hslua 1.1.1 in the version constraints.
